# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accolades',
            fields=[
                ('accolade_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('occurence', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionRunes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_id', models.IntegerField()),
                ('rune_id', models.IntegerField()),
                ('occurence', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_id', models.IntegerField()),
                ('total_games', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('match_id', models.BigIntegerField()),
                ('region', models.CharField(max_length=10)),
                ('season_id', models.IntegerField(default=0)),
                ('queue_id', models.IntegerField(default=0)),
                ('timestamp', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('champion_id', models.IntegerField(default=0)),
                ('item0', models.IntegerField(default=0)),
                ('item1', models.IntegerField(default=0)),
                ('item2', models.IntegerField(default=0)),
                ('item3', models.IntegerField(default=0)),
                ('item4', models.IntegerField(default=0)),
                ('item5', models.IntegerField(default=0)),
                ('item6', models.IntegerField(default=0)),
                ('spell0', models.IntegerField(default=0)),
                ('spell1', models.IntegerField(default=0)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('cs', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('wards_placed', models.IntegerField(default=0)),
                ('wards_killed', models.IntegerField(default=0)),
                ('vision_wards_bought', models.IntegerField(default=0)),
                ('game_type', models.CharField(max_length=50)),
                ('lane', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50, null=True)),
                ('winner', models.IntegerField(default=0)),
                ('is_remake', models.BooleanField(default=False)),
                ('red_team', models.CharField(max_length=300)),
                ('blue_team', models.CharField(max_length=300)),
                ('accolades', models.TextField()),
                ('metadata', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('region', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=16)),
                ('last_updated', models.IntegerField(default=0)),
                ('last_match_updated', models.BigIntegerField(default=0)),
                ('rank_s8', models.CharField(max_length=25)),
                ('rank_s7', models.CharField(max_length=25)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('icon', models.IntegerField(default=0)),
                ('time_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccolades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('region', models.CharField(max_length=10)),
                ('accolade_id', models.IntegerField()),
                ('accolade_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserChampionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('region', models.CharField(max_length=10)),
                ('season_id', models.IntegerField()),
                ('champ_id', models.IntegerField()),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('first_bloods', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('total_cs', models.IntegerField(default=0)),
                ('total_cs10', models.IntegerField(default=0)),
                ('total_cs20', models.IntegerField(default=0)),
                ('total_cs30', models.IntegerField(default=0)),
                ('game_length', models.IntegerField(default=0)),
                ('pentas', models.IntegerField(default=0)),
                ('quadras', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userchampionstats',
            unique_together=set([('user_id', 'region', 'season_id', 'champ_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='useraccolades',
            unique_together=set([('user_id', 'region', 'accolade_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='profilestats',
            unique_together=set([('user_id', 'region')]),
        ),
        migrations.AlterUniqueTogether(
            name='matches',
            unique_together=set([('user_id', 'match_id', 'region')]),
        ),
        migrations.AlterUniqueTogether(
            name='championrunes',
            unique_together=set([('champ_id', 'rune_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='championitems',
            unique_together=set([('champ_id', 'item_id')]),
        ),
    ]
