# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accolades',
            fields=[
                ('accolade_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('match_id', models.IntegerField()),
                ('region', models.CharField(max_length=10)),
                ('season_id', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('item0', models.IntegerField()),
                ('item1', models.IntegerField()),
                ('item2', models.IntegerField()),
                ('item3', models.IntegerField()),
                ('item4', models.IntegerField()),
                ('item5', models.IntegerField()),
                ('item6', models.IntegerField()),
                ('spell0', models.IntegerField()),
                ('spell1', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('level', models.IntegerField()),
                ('wards_placed', models.IntegerField()),
                ('wards_killed', models.IntegerField()),
                ('vision_wards_bought', models.IntegerField()),
                ('game_type', models.CharField(max_length=50)),
                ('red_players', models.CharField(max_length=300)),
                ('blue_players', models.CharField(max_length=300)),
                ('accolades', models.TextField()),
                ('metadata', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('region', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=16)),
                ('last_updated', models.IntegerField()),
                ('last_match_updated', models.IntegerField()),
                ('rank_s8', models.CharField(max_length=25)),
                ('rank_s7', models.CharField(max_length=25)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('icon', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccolades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('region', models.CharField(max_length=10)),
                ('accolade_id', models.IntegerField()),
                ('accolade_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserChampionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('region', models.CharField(max_length=10)),
                ('season_id', models.IntegerField()),
                ('champ_id', models.IntegerField()),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('first_bloods', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('total_cs', models.IntegerField(default=0)),
                ('total_cs10', models.IntegerField(default=0)),
                ('total_cs20', models.IntegerField(default=0)),
                ('total_cs30', models.IntegerField(default=0)),
                ('game_length', models.IntegerField(default=0)),
                ('pentas', models.IntegerField(default=0)),
                ('quadras', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userchampionstats',
            unique_together=set([('user_id', 'region', 'season_id', 'champ_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='useraccolades',
            unique_together=set([('user_id', 'region', 'accolade_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='profilestats',
            unique_together=set([('user_id', 'region'), ('name', 'region')]),
        ),
        migrations.AlterUniqueTogether(
            name='matches',
            unique_together=set([('user_id', 'match_id', 'region')]),
        ),
    ]
