# Generated by Django 2.0 on 2019-04-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='user_id',
            field=models.CharField(max_length=47),
        ),
        migrations.AlterField(
            model_name='matchlawn',
            name='user_id',
            field=models.CharField(max_length=47),
        ),
        migrations.AlterField(
            model_name='profilestats',
            name='user_id',
            field=models.CharField(max_length=47),
        ),
        migrations.AlterField(
            model_name='useraccolades',
            name='user_id',
            field=models.CharField(max_length=47),
        ),
        migrations.AlterField(
            model_name='userchampionitems',
            name='user_id',
            field=models.CharField(max_length=47),
        ),
        migrations.AlterField(
            model_name='userchampionmasteries',
            name='user_id',
            field=models.CharField(max_length=47),
        ),
        migrations.AlterField(
            model_name='userchampionrunes',
            name='user_id',
            field=models.CharField(max_length=47),
        ),
        migrations.AlterField(
            model_name='userchampionstats',
            name='user_id',
            field=models.CharField(max_length=47),
        ),
        migrations.AlterField(
            model_name='userchampionsummoners',
            name='user_id',
            field=models.CharField(max_length=47),
        ),
        migrations.AlterField(
            model_name='userchampionversusstats',
            name='user_id',
            field=models.CharField(max_length=47),
        ),
        migrations.AlterField(
            model_name='userleagues',
            name='user_id',
            field=models.CharField(max_length=47),
        ),
    ]
