# Generated by Django 2.0 on 2018-02-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championstats',
            name='id',
        ),
        migrations.RemoveField(
            model_name='items',
            name='id',
        ),
        migrations.AlterField(
            model_name='championstats',
            name='champ_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
