# Generated by Django 2.0 on 2018-03-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlawn',
            name='date',
            field=models.TextField(),
        ),
    ]
