# Generated by Django 2.0 on 2018-02-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='champion_id',
            new_name='champ_id',
        ),
    ]
