# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180108_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='blue_team',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='matches',
            name='red_team',
            field=models.TextField(),
        ),
    ]
