# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171127_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestats',
            name='icon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilestats',
            name='last_match_updated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilestats',
            name='last_updated',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
