# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171125_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestats',
            name='last_updated',
            field=models.DateField(blank=True),
        ),
    ]
