# Generated by Django 2.0 on 2018-02-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180211_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='participant_id',
            field=models.IntegerField(default=0),
        ),
    ]
