# Generated by Django 2.0 on 2018-02-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_matches_participant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championstats',
            name='total_games',
            field=models.IntegerField(default=0),
        ),
    ]
