# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171127_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='match_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='profilestats',
            name='icon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profilestats',
            name='last_match_updated',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
