# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180206_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChampionSummoners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('region', models.CharField(max_length=10)),
                ('champ_id', models.IntegerField()),
                ('season_id', models.IntegerField()),
                ('lane', models.CharField(max_length=50)),
                ('summoner_set', models.TextField()),
                ('occurence', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='userchampionstats',
            name='lane_bot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userchampionstats',
            name='lane_jg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userchampionstats',
            name='lane_mid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userchampionstats',
            name='lane_top',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='userchampionrunes',
            unique_together=set([('user_id', 'region', 'season_id', 'champ_id', 'lane', 'rune_set')]),
        ),
        migrations.AlterUniqueTogether(
            name='userchampionsummoners',
            unique_together=set([('user_id', 'region', 'season_id', 'champ_id', 'lane', 'summoner_set')]),
        ),
    ]
